In [1]:
import pandas as pd
import numpy as ns

In [6]:
temperatures_w1 = ns.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
(temperatures_w1)

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [7]:
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number Of Elements:", temperatures_w1.size)

Shape: (7,)
Data Type: float64
Number Of Elements: 7


In [10]:
temperatures_F = (temperatures_w1 * 9/5) + 32

print(temperatures_F )

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [13]:
temperatures_max = ns.max(temperatures_w1)
temperatures_min = ns.min(temperatures_w1)
temperatures_mean = ns.average(temperatures_w1)

print("Max:", temperatures_max)
print("Min:", temperatures_min)
print("Mean:", temperatures_mean)

Max: 26.1
Min: 20.8
Mean: 23.542857142857144


In [14]:
print(temperatures_w1[0:3])

[22.5 25.3 20.8]


In [17]:
print(temperatures_w1[-2:])

[24.8 21.9]


In [18]:
print(temperatures_w1[2:5])

[20.8 23.4 26.1]


In [19]:
temperatures = ns.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # Week 2
])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [20]:
print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

Shape: (2, 7)
Data type: float64
Total number of elements: 14


In [21]:

print("Week 1:", temperatures[0])
print("Week 2:", temperatures[1])
print("Week 1 Weekend:", temperatures[0, -2:])
print("Week 2 Weekend:", temperatures[1, -2:])

Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Week 1 Weekend: [24.8 21.9]
Week 2 Weekend: [22.8 20.1]


In [24]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [ ]:
print(marks.iloc[0])


In [25]:
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [27]:
print(marks.iloc[2])

89


In [28]:
print(marks[marks > 90])

Rank1    95
Rank2    92
dtype: int64


In [29]:
marks.loc['Rank1'] = 100
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [30]:
marks = marks.drop('Rank5')
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [31]:
cgpa = marks / 10
print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [32]:
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [33]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   TransactionID    10 non-null     int64 
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [34]:

print(transactions)
print(transactions.head())
print(transactions.tail())
print(transactions.shape)
print(transactions.columns)
print(transactions.dtypes)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West 

In [35]:
print(transactions[['ProductCategory', 'Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [36]:
print(transactions.iloc[:, -3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [37]:
filtered_rows = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print(filtered_rows)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [38]:
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [39]:
print(transactions['Region'].unique())

['North' 'South' 'East' 'West']


In [40]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [44]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [46]:
transactions['Discount'] = transactions['Amount'] * 0.10
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [47]:
transactions = transactions[transactions['TransactionID'] != 109]
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [51]:
transactions = transactions.drop('Discount', axis=1)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
